config/routes.rb
# frozen_string_literal: true

# Copyright 2019 Andrew Esler (ajesler)
# Copyright 2019 Matthew B. Gray
# Copyright 2019 Steven C Hartley
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# For more information about routes, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root to: "landing#index"

  # Sets routes for account management actions.
  # This order seems to matter for tests.
  devise_for :users
  devise_for :supports

  get "/login/:email/:key", to: "user_tokens#kansa_login_link", email: /[^\/]+/, key: /[^\/]+/
  resources :user_tokens, only: [:new, :show, :create], id: /[^\/]+/ do
    get :logout, on: :collection
  end

  resources :charges
  resources :credits
  resources :landing
  resources :memberships
  resources :themes
  resources :upgrades

  resources :reservations do
    resources :upgrades
  end

  # /operator are maintenance routes for support people
  scope :operator do
    resources :reservations do
      resources :credits
      resources :set_memberships
      resources :transfers, id: /[^\/]+/
    end
  end
end

app/models/charge.rb
# frozen_string_literal: true

# Copyright 2019 AJ Esler
# Copyright 2019 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class Charge < ApplicationRecord
  STATE_FAILED = "failed"
  STATE_SUCCESSFUL = "successful"
  STATE_PENDING = "pending"
  TRANSFER_STRIPE = "stripe"
  TRANSFER_CASH = "cash"

  belongs_to :user
  belongs_to :reservation

  monetize :amount_cents

  validates :amount, presence: true
  validates :comment, presence: true
  validates :state, inclusion: {in: [STATE_FAILED, STATE_SUCCESSFUL, STATE_PENDING]}
  validates :stripe_id, presence: true, if: :stripe?
  validates :transfer, presence: true, inclusion: {in: [TRANSFER_STRIPE, TRANSFER_CASH]}

  scope :stripe, ->() { where(transfer: TRANSFER_STRIPE) }
  scope :cash, ->() { where(transfer: TRANSFER_CASH) }
  scope :pending, ->() { where(state: STATE_PENDING) }
  scope :failed, ->() { where(state: STATE_FAILED) }
  scope :successful, ->() { where(state: STATE_SUCCESSFUL) }

  def stripe?
    transfer == TRANSFER_STRIPE
  end

  def cash?
    transfer == TRANSFER_CASH
  end

  def successful?
    state == STATE_SUCCESSFUL
  end

  def pending?
    state == STATE_PENDING
  end
end

app/controllers/charges_controller.rb
# frozen_string_literal: true

# Copyright 2019 AJ Esler
# Copyright 2019 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Test cards are here: https://stripe.com/docs/testing
class ChargesController < ApplicationController
  def new
    @reservation = current_user.reservations.find(params[:reservation])

    if @reservation.paid?
      redirect_to reservations_path, notice: "You've paid for this #{@reservation.membership} membership"
      return
    end

    @membership = @reservation.membership
    @outstanding_amount = AmountOwedForReservation.new(@reservation).amount_owed

    price_steps = PaymentAmountOptions.new(@outstanding_amount).amounts

    @price_options = price_steps.reverse.map do |price|
      [price.format, price.cents]
    end
  end

  def create
    reservation = current_user.reservations.find(params[:reservation])
    charge_amount = Money.new(params[:amount].to_i)

    outstanding_before_charge = AmountOwedForReservation.new(reservation).amount_owed

    allowed_charge_amounts = PaymentAmountOptions.new(outstanding_before_charge).amounts
    if !allowed_charge_amounts.include?(charge_amount)
      flash[:error] =  "Amount must be one of the provided payment amounts"
      redirect_to new_charge_path(reservation: reservation)
      return
    end

    service = Money::ChargeCustomer.new(
      reservation,
      current_user,
      params[:stripeToken],
      outstanding_before_charge,
      charge_amount: charge_amount,
    )

    charge_successful = service.call
    if !charge_successful
      flash[:error] = service.error_message
      redirect_to new_charge_path(reservation: reservation)
      return
    end

    if reservation.instalment?
      PaymentMailer.instalment(
        user: current_user,
        charge: service.charge,
        outstanding_amount: (outstanding_before_charge - charge_amount).format(with_currency: true)
      ).deliver_later
    else
      PaymentMailer.paid(
        user: current_user,
        charge: service.charge,
      ).deliver_later
    end

    message = "Thank you for your #{charge_amount.format} payment"
    (message += ". Your #{reservation.membership} membership has been paid for.") if reservation.paid?
    redirect_to reservations_path, notice: message
  end
end

app/helpers/charges_helper.rb
# frozen_string_literal: true

# Copyright 2019 Matthew B. Gray
# Copyright 2019 AJ Esler
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module ChargesHelper
  def stripe_config(reservation)
    {
      key: Rails.configuration.stripe[:publishable_key],
      description: "CoNZealand #{@membership.name} membership",
      email: reservation.user.email,
      currency: $currency,
    }.to_json
  end
end

app/views/charges/new.html.erb
<%
# Copyright 2019 AJ Esler
# Copyright 2019 Matthew B. Gray
# Copyright 2019 Jen Zajac (jenofdoom)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
%>

<h1>Make a Payment towards Membership #<%= @reservation.membership_number %></h1>
<section class="l-section">
  <div class="row">
    <div class="col-12 col-lg-8">
      <div class="l-panel">
        <%= form_tag(charges_path, "id" => "charge-form", "data-stripe" => stripe_config(@reservation)) do %>
          <article>
            <div id="error_explanation"></div>

            <p>
              You need to pay <%= @outstanding_amount.format(with_currency: true) %> to cover this membership. Please pay
              the full amount, or choose an instalment from the list.
            </p>

            <label class="amount">
              <span>Amount:
                <%= select_tag(:amount, options_for_select(@price_options, selected: @outstanding_amount)) %>
              </span>
            </label>
          </article>

          <%= hidden_field_tag(:stripeToken) %>
          <%= hidden_field_tag(:stripeEmail) %>
          <%= hidden_field_tag(:reservation, @reservation.id) %>
          <div class="l-v-spacing-both">
            <div class="form-group">
              <%= submit_tag("Pay for #{@membership} membership", id: "reservation-button", class: "btn btn-m-full-width") %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-12 col-lg-4">
      <div class="l-v-spacing">
        <%= render("reservation_card", reservation: @reservation) %>
      </div>
    </div>
  </div>
</section>